api/urls.py
from django.urls import path, include, re_path
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', views.apiOverview, name='api-overview'),

	path('tag-list/', views.tagList, name='tag-list'),
	path('tag-detail/<str:pk>/', views.tagDetail, name='tag-detail'),
	path('tag-create/', views.tagCreate, name='tag-create'),
	path('tag-delete/<str:pk>/', views.tagDelete, name='tag-delete'),
	path('tag-update/<str:pk>/', views.tagUpdate, name='tag-update'),

	path('form-list/', views.formList, name='form-list'),
	path('form-detail/<str:pk>/', views.formDetail, name='form-detail'),
	path('form-create/', views.formCreate, name='form-create'),
	path('form-delete/<str:pk>/', views.formDelete, name='form-delete'),
	path('form-update/<str:pk>/', views.formUpdate, name='form-update'),

	path('uploadForm/', views.uploadForm, name = 'uploadForm'),

	path('link-list/', views.linkList, name='link-list'),
	path('link-detail/<str:pk>/', views.linkDetail, name='link-detail'),
	path('link-create/', views.linkCreate, name='link-create'),
	path('link-delete/<str:pk>/', views.linkDelete, name='link-delete'),
	path('link-update/<str:pk>/', views.linkUpdate, name='link-update'),

	path('uploadTraining/', views.uploadTraining, name = 'uploadTraining'),
	path('content-list/', views.contentList, name = 'content-list'),
	path('content-detail/<str:pk>/', views.contentDetail, name='content-detail'),
	path('content-delete/<str:pk>/', views.contentDelete, name='content-delete'),
	path('content-update/<str:pk>/', views.contentUpdate, name='content-update'),

	path('subject-list/', views.subjectList, name = 'subject-list'),

	path('form2-list/', views.form2List, name='form2-list'),
	path('form2-detail/<str:pk>/', views.form2Detail, name='form2-detail'),
	path('form2-delete/<str:pk>/', views.form2Delete, name='form2-delete'),
	path('form2-update/<str:pk>/', views.form2Update, name='form2-update'),
	path('uploadResource/', views.uploadResourceFunc, name='uploadResource'),

	path('contact-list/', views.contactList, name='contact-list'),
	path('contact-detail/<str:pk>/', views.contactDetail, name='contact-detail'),
	path('contact-create/', views.contactCreate, name='contact-create'),
	path('contact-delete/<str:pk>/', views.contactDelete, name='contact-delete'),
	path('contact-update/<str:pk>/', views.contactUpdate, name='contact-update'),
]

armUserFacing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
] 

api/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import date

# Create your models here.

class FormTags(models.Model):
	name = models.CharField(max_length = 300)

	def __str__(self):
		return self.name


class Form(models.Model):
	title = models.CharField(max_length = 300, null = True)
	file = models.FileField(upload_to = "documents/", null = True)
	date = models.DateField(auto_now_add = True, null = True)
	tag = models.ManyToManyField(FormTags)

	def __str__(self):
		return self.title


class Link(models.Model):
	title = models.CharField(max_length = 300)
	url = models.CharField(max_length = 600)
	date = models.DateField(auto_now_add = True)

	def __str__(self):
		return self.title


class Subject(models.Model):
	name = models.CharField(max_length = 300)

	def __str__(self):
		return self.name


class Content(models.Model):
	title = models.CharField(max_length = 300, null = True)
	file = models.FileField(upload_to = "documents/training/", null = True)
	file2 = models.FileField(upload_to = "documents/training/", null = True, blank = True)
	date = models.DateField(auto_now_add = True, null = True)
	subject = models.ManyToManyField(Subject)

	def __str__(self):
		return self.title


class Form2(models.Model):
	title = models.CharField(max_length = 300, null = True)
	file = models.FileField(upload_to = "documents/resourceForms/", null = True)
	date = models.DateField(auto_now_add = True, null = True)

	def __str__(self):
		return self.title
	

class Contact(models.Model):
	email = models.CharField(max_length = 300, null = True)
	name = models.CharField(max_length = 300, null = True)
	number = models.CharField(max_length = 300, null = True)
	speciality = models.TextField(max_length = 300, null = True)

	def __str__(self):
		return self.name

api/forms.py
from django.forms import ModelForm
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django import forms


class upload(ModelForm):
	class Meta:
		model = Form
		fields = '__all__'
		exclude = ['date']


class uploadTrainingContent(ModelForm):
	class Meta:
		model = Content
		fields = '__all__'
		exclude = ['date']


class uploadResourceForm(ModelForm):
	class Meta:
		model = Form2
		fields = '__all__'
		exclude = ['date']

api/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib.auth.models import User

from rest_framework.decorators import api_view, authentication_classes, parser_classes, renderer_classes
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.renderers import MultiPartRenderer

from .serializers import *
from .models import *
from .forms import *
# Create your views here.


@api_view(['GET'])
def apiOverview(request):
	api_urls = {
		'Form List': '/form-list/',
		'form Detail': '/form-detail/<str:pk>/',
		'Create form': 'form-create/',
		'Update form': 'form-update/<str:pk>/',
		'Delete form': 'form-delete/<str:pk>/',

		'Tag List': '/tag-list/',
		'Tag Detail': '/tag-detail/<str:pk>/',
		'Create tag': 'tag-create/',
		'Update tag': 'tag-update/<str:pk>/',
		'Delete tag': 'tag-delete/<str:pk>/',

		'Link List': '/link-list',
		'Link Detail': '/link-detail/<str:pk>/',
		'Create link':'/link-create/',
		'Update link': '/link-update/<str:pk>/',
		'Delete link': '/link-delete/<str:pk>/',

		'Training List': '/content-list',
		'Training Detail': '/training-list',
		'Update Training': '/training-update',
		'Delete Training': '/training-delete',
		'Subject List': '/subject-list',

		'Resource List':'/form2-list/',
		'Resource Detail': '/form2-detail/<str:pk>/',
		'Update Resource': '/form2-update/<str:pk>/',
		'Delete Resource': '/form2-delete/',
	}
	return Response(api_urls)


@api_view(['GET'])
def linkList(request):
	links = Link.objects.all().order_by('title')
	serializer = LinkSerializer(links, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def linkDetail(request, pk):
	link = Link.objects.get(id = pk)
	serializer = LinkSerializer(link, many=False)

	return Response(serializer.data)


@api_view(['POST'])
def linkCreate(request):
	serializer = LinkSerializer(data=request.data, many=False)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['POST'])
def linkUpdate(request, pk):
	link = Link.objects.get(id=pk)
	serializer = LinkSerializer(instance = link, data=request.data, partial=True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def linkDelete(request, pk):
	link = Link.objects.get(id=pk)
	link.delete()

	return Response('Item Successfully Deleted')


@api_view(['GET'])
def contactList(request):
	contacts = Contact.objects.all().order_by('name')
	serializer = ContactSerializer(contacts, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def contactDetail(request, pk):
	contact = Contact.objects.get(id = pk)
	serializer = ContactSerializer(contact, many = False)

	return Response(serializer.data)


@api_view(['POST'])
def contactCreate(request):
	serializer = ContactSerializer(data = request.data, many=False)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['POST'])
def contactUpdate(request, pk):
	contact = Contact.objects.get(id=pk)
	serializer = ContactSerializer(instance=contact, data = request.data, partial=True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def contactDelete(request, pk):
	contact = Contact.objects.get(id=pk)
	contact.delete()

	return Response('Item Successfully Deleted!')


@api_view(['GET'])
def tagList(request):
	tags = FormTags.objects.all().order_by('name')
	serializer = TagSerializer(tags, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def tagDetail(request, pk):
	tags = FormTags.objects.get(id = pk)
	serializer = TagSerializer(tags, many=False)

	return Response(serializer.data)


@api_view(['POST'])
def tagCreate(request):
	serializer = TagSerializer(data=request.data, many=False)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['POST'])
def tagUpdate(request, pk):
	tag = FormTags.objects.get(id=pk)
	serializer = TagSerializer(instance=tag, data=request.data, partial=True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def tagDelete(request, pk):
	tag = FormTags.objects.get(id=pk)
	tag.delete()

	return Response('Item Successfully Deleted!')


@api_view(['GET'])
def formList(request):
	forms = Form.objects.all().order_by('title')
	serializer = FormSerializer(forms, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def formDetail(request, pk):
	forms = Form.objects.get(id = pk)
	serializer = FormSerializer(forms, many=False)

	return Response(serializer.data)


@api_view(['POST'])
@parser_classes([MultiPartParser, FormParser])
def formCreate(request):
	serializer = FormSerializer(data=request.data)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['POST'])
def formUpdate(request, pk):
	form = Form.objects.get(id=pk)
	serializer = FormSerializer(instance=form, data=request.data, partial=True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def formDelete(request, pk):
	form = Form.objects.get(id=pk)
	form.delete()

	return Response('Item Successfully Deleted!')


def uploadForm(request):
	form = upload()

	if request.method == "POST":
		form = upload(request.POST, request.FILES)
		if form.is_valid():
			print('valid')
			filename = str(request.FILES['file'])
			handle_uploaded_file(request.FILES['file'], filename)
			form.save()
			return redirect('blog:files')
		else:
			print('not valid')
			
	context = {'form':form}
	return render(request, 'api/uploadForm.html',context)


def handle_uploaded_file(f, filename):
    with open('static/images/documents/' + filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def uploadTraining(request):
	form = uploadTrainingContent()

	if request.method == "POST":
		form = uploadTrainingContent(request.POST, request.FILES)
		if form.is_valid:
			for f in request.FILES.getlist('file'):
				filename = str(f)
				handle_uploaded_content(f, filename)
			form.save()
			return redirect('blog:trainingDB')

	context = {'form':form}
	return render(request, 'api/trainingUpload.html',context)


def handle_uploaded_content(f, filename):
    with open('static/images/documents/training/' + filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


@api_view(['GET'])
def contentList(request):
	trainingContent = Content.objects.all().order_by('title')
	serializer = ContentSerializer(trainingContent, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def contentDetail(request, pk):
	trainingContent = Content.objects.get(id = pk)
	serializer = ContentSerializer(trainingContent, many = False)

	return Response(serializer.data)


@api_view(['POST'])
def contentUpdate(request, pk):
	trainingContent = Content.objects.get(id = pk)
	serializer = ContentSerializer(instance = form, data = request.data, partial = True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def contentDelete(request, pk):
	trainingContent = Content.objects.get(id = pk)
	trainingContent.delete()

	return Response('Item Successfully Deleted!')


@api_view(['GET'])
def subjectList(request):
	subjects = Subject.objects.all().order_by('name')
	serializer = SubjectSerializer(subjects, many = True)
	
	return Response(serializer.data)


@api_view(['GET'])
def form2List(request):
	forms = Form2.objects.all().order_by('title')
	serializer = Form2Serializer(forms, many=True)

	return Response(serializer.data)


@api_view(['GET'])
def form2Detail(request, pk):
	forms = Form2.objects.get(id = pk)
	serializer = Form2Serializer(forms, many=False)

	return Response(serializer.data)


@api_view(['POST'])
def form2Update(request, pk):
	form = Form2.objects.get(id=pk)
	serializer = Form2Serializer(instance=form, data=request.data, partial=True)

	if serializer.is_valid():
		serializer.save()

	return Response(serializer.data)


@api_view(['DELETE'])
def form2Delete(request, pk):
	form = Form2.objects.get(id=pk)
	form.delete()

	return Response('Item Successfully Deleted!')


def uploadResourceFunc(request):
	form = uploadResourceForm()
	if request.method == "POST":
		form = uploadResourceForm(request.POST, request.FILES)
		if form.is_valid():
			filename = str(request.FILES['file'])
			handle_uploaded_form(request.FILES['file'], filename)
			form.save()
			return redirect('blog:resourceFormUpload')

	context = {'form':form}
	return render(request, 'api/uploadResource.html',context)


def handle_uploaded_form(f, filename):
    with open('static/images/documents/resourceForms/' + filename, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

api/templates/api/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Large File Upload</title>

  </head>
  <body>
    <div class='container main-container'>
      {% block content %}{% endblock content %}
    </div>
    {% block javascript %}

    {% endblock %}
  </body>
 </html>

api/templates/api/navbar.html
{% load static %}

<style type="text/css">
  nav{
    background-color:#2e612f;
  }
  a, li{
    color:#fff !important;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-light border-btm border-dark rounded-bottom shadow">
  <a class="navbar-brand" href="#" style="text-decoration: underline;">CPFD Resource Center<i class='fas fa-seedling'></i></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'training' %}">Training</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'methods2'%}">Methodology</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Resources
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'links' %}">Forms</a>
          <a class="dropdown-item" href="{% url 'links' %}">Links</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

api/templates/api/trainingUpload.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<style>
	.main{
		justify-content: center;
		width:90%;
		margin-top:30px;
	}
	p{
		display: inline-flex;
		justify-content: space-between;
		margin:30px;
	}
	label{
		font-size: 1.5rem;
		font-weight: bold;
	}
	.custom{
		width: 90%;
		display: flex;
		justify-content: center;
		border-radius: 25px;
		border-color: #2e612f;
		border-width: 2px;
	}
	#id_title{
		width: 90%;
	}
	#id_subject{
		width: 80%;
	}
	#btnDiv{
		text-align: right;
	}
</style>


<div class = "card card-body custom main mx-auto">
	<form action='' method='POST' enctype = "multipart/form-data">
		{% csrf_token %}
		<label for="id_title">Title: </label>
		{{form.title}}
		<hr>
		<label for="id_file">Presentation File as PDF: </label>
		{{form.file}}
		<hr>
		<label for="id_file2">Accompanying Video or Secondary File: </label>
		{{form.file2}}
		<hr>
		<label for="id_subject">Subject(s): </label>
		{{form.subject}}
		<br>
		<hr>

		<div id="btnDiv">
			<input class="btn btn-primary btn-lg" type="submit" name="Upload" value ="Upload">
		</div>
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#id_subject').select2();
	})
</script>

{% endblock %}

api/templates/api/upload.html
{% extends "api/base.html" %}
{% block content %}
<div class='row'>
    <div class='col-6 offset-3'>
        <div class='item-loading-queue'>

        </div>
        <form class='upload-form'>
            <input class='upload-file form-control' type='file' accept='audio/*,video/*,image/*' multiple='multiple'/>
        </form>
    </div>
</div>
{% endblock content %}
{% block javascript %}
<script>
    $(document).ready(function(){

        // setup session cookie data. This is Django-related
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        // end session cookie data setup. 



    // declare an empty array for potential uploaded files
    var fileItemList = []

    // auto-upload on file input change.
    $(document).on('change','.upload-file', function(event){
        var selectedFiles = $(this).prop('files');
        formItem = $(this).parent()
        $.each(selectedFiles, function(index, item){
            var myFile = verifyFileIsImageMovieAudio(item)
            if (myFile){
                uploadFile(myFile)
            } else {
                // alert("Some files are invalid uploads.")
            }
        })
        $(this).val('');

    })



    function verifyFileIsImageMovieAudio(file){
        // verifies the file extension is one we support.
        var extension = file.name.split('.').pop().toLowerCase(); //file.substr( (file.lastIndexOf('.') +1) );
        switch(extension) {
            case 'jpg':
            case 'png':
            case 'gif':
            case 'jpeg':
                return file  
            case 'mov':
            case 'mp4':
            case 'mpeg4':
            case 'avi':
                return file
            case 'mp3':
                return file
            default:
                notAllowedFiles.push(file)
                return null
        }
    };

    function constructFormPolicyData(policyData, fileItem) {
       var contentType = fileItem.type != '' ? fileItem.type : 'application/octet-stream'
        var url = policyData.url
        var filename = policyData.filename
        var repsonseUser = policyData.user
        // var keyPath = 'www/' + repsonseUser + '/' + filename
        var keyPath = policyData.file_bucket_path
        var fd = new FormData()
        fd.append('key', keyPath + filename);
        fd.append('acl','private');
        fd.append('Content-Type', contentType);
        fd.append("AWSAccessKeyId", policyData.key)
        fd.append('Policy', policyData.policy);
        fd.append('filename', filename);
        fd.append('Signature', policyData.signature);
        fd.append('file', fileItem);
        return fd
    }

    function fileUploadComplete(fileItem, policyData){
        console.log(fileItem, policyData);
        data = {
            uploaded: true,
            fileSize: fileItem.size,
            file: policyData.file_id,

        }
        $.ajax({
            method:"POST",
            data: data,
            url: "/api/files/complete/",
            success: function(data){
                displayItems(fileItemList)
            },
            error: function(jqXHR, textStatus, errorThrown){ 
                alert("An error occured, please refresh the page.")
            }
        })
    }

    function displayItems(fileItemList){
        var itemList = $('.item-loading-queue')
        itemList.html("")
        $.each(fileItemList, function(index, obj){
            var item = obj.file
            var id_ = obj.id
            var order_ = obj.order
            var html_ = "<div class=\"progress\">" + 
              "<div class=\"progress-bar\" role=\"progressbar\" style='width:" + item.progress + "%' aria-valuenow='" + item.progress + "' aria-valuemin=\"0\" aria-valuemax=\"100\"></div></div>"
            itemList.append("<div>" + order_ + ") " + item.name + "<a href='#' class='srvup-item-upload float-right' data-id='" + id_ + ")'>X</a> <br/>" + html_ + "</div><hr/>")

        })
    }


    function uploadFile(fileItem){
            var policyData;
            var newLoadingItem;
            // get AWS upload policy for each file uploaded through the POST method
            // Remember we're creating an instance in the backend so using POST is
            // needed.
            $.ajax({
                method:"POST",
                data: {
                    filename: fileItem.name
                },
                url: "/api/files/policy/",
                success: function(data){
                    policyData = data
                },
                error: function(data){
                    alert("An error occured, please try again later. No complete")
                }
            }).done(function(){
                // construct the needed data using the policy for AWS
                var fd = constructFormPolicyData(policyData, fileItem)
                
                // use XML http Request to Send to AWS. 
                var xhr = new XMLHttpRequest()

                // construct callback for when uploading starts
                xhr.upload.onloadstart = function(event){
                    var inLoadingIndex = $.inArray(fileItem, fileItemList)
                    if (inLoadingIndex == -1){
                        // Item is not loading, add to inProgress queue
                        newLoadingItem = {
                            file: fileItem,
                            id: policyData.file_id,
                            order: fileItemList.length + 1
                        }
                        fileItemList.push(newLoadingItem)
                      }
                    fileItem.xhr = xhr
                }

                // Monitor upload progress and attach to fileItem.
                xhr.upload.addEventListener("progress", function(event){
                    if (event.lengthComputable) {
                     var progress = Math.round(event.loaded / event.total * 100);
                        fileItem.progress = progress
                        displayItems(fileItemList)
                    }
                })

                xhr.upload.addEventListener("load", function(event){
                    console.log("Complete")
                    // handle FileItem Upload being complete.
                    fileUploadComplete(fileItem, policyData)

                })

                xhr.open('POST', policyData.url , true);
                xhr.send(fd);
            })
    }});
</script>
{% endblock %}

api/templates/api/uploadForm.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>


<style>
	.main{
		justify-content: center;
		width:90%;
		margin-top:30px;
	}
	p{
		display: inline-flex;
		justify-content: space-between;
		margin:30px;
	}
	label{
		font-size: 1.5rem;
		font-weight: bold;
	}
	.custom{
		width: 90%;
		display: flex;
		justify-content: center;
		border-radius: 25px;
		border-color: #2e612f;
		border-width: 2px;
	}
	#id_title{
		width:90%;
		display:inline-block;
	}
	#id_tag{
		width:50%;
	}
	#button{
		text-align: right;
	}
</style>


<div class = "card card-body custom main mx-auto">
	<form action='#' method='POST' enctype = "multipart/form-data">
		{% csrf_token %}
		<label for="id_title">Title:</label>
		{{form.title}}
		<hr>
		<label for="id_tag">Tags:</label>
		{{form.tag}}
		<hr>
		<label for="id_file">File:</label>
		{{form.file}}
		<hr>
		<div id="button">
			<input style="justify-content: right" class="btn btn-primary btn-lg" type="submit" name="Upload" value ="Upload">
		</div>
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#id_tag').select2();
	})
</script>

{% endblock %}

api/templates/api/uploadResource.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<style>
	.main{
		justify-content: center;
		width:90%;
		margin-top:30px;
	}
	p{
		display: inline-flex;
		justify-content: space-between;
		margin:30px;
	}
	label{
		font-size: 1.5rem;
		font-weight: bold;
	}
	.custom{
		width: 90%;
		display: flex;
		justify-content: center;
		border-radius: 25px;
		border-color: #2e612f;
		border-width: 2px;
	}
	#button{
		text-align: right;
	}
	#id_title{
		width: 90%;
	}
</style>


<div class = "card card-body custom main mx-auto">
	<form action='' method='POST' enctype = "multipart/form-data">
		{% csrf_token %}
		<label for="id_title">Title: </label>
		{{form.title}}
		<hr>
		<label for="id_file">File as PDF: </label>
		{{form.file}}
		<hr>
		<div id="button">
			<input class="btn btn-primary btn-lg" type="submit" name="Upload" value ="Upload">
		</div>
	</form>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('#id_subject').select2();
	})
</script>

{% endblock %}