api/urls.py
from django.urls import path, include, re_path
from . import views
from django.views.generic.base import TemplateView

urlpatterns = [
	path('', views.apiOverview, name='api-overview'),

	path('tag-list/', views.tagList, name='tag-list'),
	path('tag-detail/<str:pk>/', views.tagDetail, name='tag-detail'),
	path('tag-create/', views.tagCreate, name='tag-create'),
	path('tag-delete/<str:pk>/', views.tagDelete, name='tag-delete'),
	path('tag-update/<str:pk>/', views.tagUpdate, name='tag-update'),

	path('form-list/', views.formList, name='form-list'),
	path('form-detail/<str:pk>/', views.formDetail, name='form-detail'),
	path('form-create/', views.formCreate, name='form-create'),
	path('form-delete/<str:pk>/', views.formDelete, name='form-delete'),
	path('form-update/<str:pk>/', views.formUpdate, name='form-update'),

	path('uploadForm/', views.uploadForm, name = 'uploadForm'),

	path('link-list/', views.linkList, name='link-list'),
	path('link-detail/<str:pk>/', views.linkDetail, name='link-detail'),
	path('link-create/', views.linkCreate, name='link-create'),
	path('link-delete/<str:pk>/', views.linkDelete, name='link-delete'),
	path('link-update/<str:pk>/', views.linkUpdate, name='link-update'),

	path('uploadTraining/', views.uploadTraining, name = 'uploadTraining'),
	path('content-list/', views.contentList, name = 'content-list'),
	path('content-detail/<str:pk>/', views.contentDetail, name='content-detail'),
	path('content-delete/<str:pk>/', views.contentDelete, name='content-delete'),
	path('content-update/<str:pk>/', views.contentUpdate, name='content-update'),

	path('subject-list/', views.subjectList, name = 'subject-list'),

	path('form2-list/', views.form2List, name='form2-list'),
	path('form2-detail/<str:pk>/', views.form2Detail, name='form2-detail'),
	path('form2-delete/<str:pk>/', views.form2Delete, name='form2-delete'),
	path('form2-update/<str:pk>/', views.form2Update, name='form2-update'),
	path('uploadResource/', views.uploadResourceFunc, name='uploadResource'),

	path('contact-list/', views.contactList, name='contact-list'),
	path('contact-detail/<str:pk>/', views.contactDetail, name='contact-detail'),
	path('contact-create/', views.contactCreate, name='contact-create'),
	path('contact-delete/<str:pk>/', views.contactDelete, name='contact-delete'),
	path('contact-update/<str:pk>/', views.contactUpdate, name='contact-update'),
]

armUserFacing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('microsoft/', include('microsoft_auth.urls', namespace='microsoft')),
] 

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path('', views.home, name = 'home'),
	path('blog/', views.blog, name = 'blog'),
	path('files/', views.files, name='files'),
	path('train/', views.training, name = 'training'),
	path('methods/', views.methods, name= 'methods'),
	path('display/<str:pk>/', views.display, name='display'),
	path('display2/<str:pk>/', views.display2, name='display2'),
	path('display3/<str:pk>/', views.display3, name='display3'),
	path('display4/<str:pk>/', views.display4, name='display4'),
	path('tagDB/', views.tagDB, name = 'tagDB'),
	path('search/<str:pk>/', views.search, name = 'search'),
	path('search/<str:pk>/', views.search, name = 'search'),
	path('resources/', views.resources, name='resources'),
	path('links/', views.links, name='links'),
	path('forms/', views.forms, name='forms'),
	path('login/', views.login, name='login'),
	path('trainingDB/', views.trainingUpload, name='trainingDB'),
	path('resourceFormUpload/', views.resourceFormUpload, name='resourceFormUpload'),
	path('linkUpload/', views.linkUpload, name='linkUpload'),
	path('support/', views.support, name='support'),
	path('supportAdmin/', views.supportAdmin, name='supportAdmin'),
	path('calculator/', views.calculator, name='calculator'),
]

blog/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	txt = models.TextField()
	asked = models.DateTimeField(auto_now_add = True)


class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete = models.CASCADE)
	answer = models.TextField()
	answered = models.DateTimeField(auto_now_add = True)


class Announcement(models.Model):
	headline = models.TextField()
	body = models.TextField(null = True)
	link = models.CharField(max_length = 200, null = True, blank = True)

	

blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from rest_framework.parsers import MultiPartParser
# Create your views here.
from .models import *
from api.models import *
from api.serializers import *
from django.views.decorators.clickjacking import xframe_options_exempt
import json

def login(request):
	return render(request, 'blog/home.html')

def home(request):
	objs = Announcement.objects.values()
	x = 0; d = {};
	for y in objs:
		d[x] = y
		x+=1

	methods = Form.objects.count()
	links = Link.objects.count()
	contents = Content.objects.count()
	forms = Form2.objects.count()

	context = {'text': json.dumps(d),'forms':[forms,links,contents,methods]}
	return render(request, 'blog/home2.html', context)


def methods(request):
	return	render(request,'blog/methods.html')


def training(request):
	return render(request, 'blog/training.html')


def files(request):
	return render(request, 'blog/files.html')


def display(request, pk):
	url = 'http://172.20.57.135:88/api/form-detail/' + pk + '/'
	context = {'url':url}
	return render(request, 'blog/display.html', context)


def display2(request, pk):
	url = 'http://172.20.57.135:88/api/content-detail/' + pk + '/'
	context = {'url':url}
	return render(request, 'blog/display.html', context)


def display3(request, pk):
	url = 'http://172.20.57.135:88/api/form2-detail/' + pk + '/'
	context = {'url':url}
	return render(request, 'blog/display.html', context)

def display4(request, pk):
	url = 'http://172.20.57.135:88/api/content-detail/' + pk + '/'
	context = {'url':url}
	return render(request, 'blog/display4.html', context)


def tagDB(request):
	return render(request,'blog/tag.html')


def resources(request):
	return render(request, 'blog/resources.html')


def links(request):
	return render(request, 'blog/links.html')


def blog(request):
	return HttpResponse('This will be the blog')


def search(request, pk):
	context = {'pk':pk}
	return render(request, 'blog/search.html', context)


def forms(request):
	return render(request, 'blog/forms.html')


def trainingUpload(request):
	return render(request, 'blog/trainingUpload.html')


def resourceFormUpload(request):
	return render(request, 'blog/resourceFormUpload.html')


def linkUpload(request):
	return render(request, 'blog/linkUpload.html')


def support(request):
	return render(request, 'blog/supportUser.html')


def supportAdmin(request):
	return render(request, 'blog/support.html')


def calculator(request):
	return render(request, 'blog/calculator.html')

blog/templates/blog/display.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	iframe {
		border: 4px solid #fff;
		outline: 4px solid #526927;
	}
</style>

<br>
<br>

<div class="container">
	<iframe class = "shadow-lg" id="frame" width='100%' height='600px' frameborder='0'></iframe>
</div>


<script type="text/javascript">
	console.log("{{url}}")
	fetch("{{url}}")
	.then((resp) => resp.json())
	.then(function(data){
		var src = `http://172.20.57.135:88/static${data.file}`;
		console.log(src);
		document.getElementById("frame").src = src;
	})
</script>

{% endblock %}

blog/templates/blog/home.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<style>
	.flex-container{
		display: flex;
		justify-content: center;
	}
	.img-wrapper{
		justify-content: center;
		padding:0px;
		background-color: #fff;
	}
	.href{
		justify-content: center;
		margin-left: 30px;
		margin-right: 30px;
		border: 3px solid  white;
		outline: 3px solid #829986;
	}
</style>
<hr>
<br>
<br>
<div class = "flex-container">
	<a class="href shadow-lg" href="{% url 'blog:methods' %}">
		<span>
			<img src="{% static 'images/method2.png' %}" class="img-fluid mx-auto d-block">
		</span>
	</a>
	<a class="href shadow-lg" href="{% url 'blog:resources' %}">
		<span>
			<img src="{% static 'images/resources.png' %}" class="img-fluid mx-auto d-block">
		</span>
	</a>
	<a class="href shadow-lg" href="{% url 'blog:training' %}">
		<span>
			<img src="{% static 'images/learning.png' %}" class="img-fluid mx-auto d-block">
		</span>
	</a>
	<hr>
</div>
<script type="text/javascript">
	var navBar = document.getElementById('navDiv').innerHTML;
	var newBar = `
		<div>
			${navBar}
		</div>`
	document.getElementById('navDiv').innerHTML = newBar;
	document.getElementById('home').remove();

</script>
{% endblock %}

blog/templates/blog/home2.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<style>
	body{
		overflow-x: hidden;
	}
	.flex-container{
		display: inline-flex;
		margin-left: 3%;
		margin-right: 3%;
	}
	.href{
		border: 3px solid white;
		outline: 3px solid #829986;
		padding-left:0;
		margin-bottom:1em;
		height: auto;
		max-width: 90%;
	}
	
	.slide{
		border: 3px solid white;
		outline: 3px solid #829986;
		height: auto;
		width: auto;
		max-height: 50%;
		max-width: 50%;
		margin-top:1em;
	}
	.carousel {
		width: 60%;
		height: 60%;
	}
	h6{
		font-weight: 700;
		color:black;
		font-family: Rockwell, "Courier New", Courier, Georgia, Times, "Times New Roman", serif;
	}
	p{
		color:black;
		font-family: Rockwell, "Courier New", Courier, Georgia, Times, "Times New Roman", serif;
	}
	.topics{
		margin-left: 5%;
	}
	.indicator{
		background-color: #526927 !important;
	}
	.carousel-control-prev-icon,
	.carousel-control-next-icon {
	  height: 100px;
	  width: 100px;
	  background-size: 100%, 100%;
	  background-image: none;
	}
	.carousel-control-next-icon:after
	{
	  content: '>';
	  font-size: 55px;
	  color: #526927;
	}
	.carousel-control-prev-icon:after {
	  content: '<';
	  font-size: 55px;
	  color: #526927;
	}
	.carousel-caption{
		top: 50%;
		transform: translateY(-50%);
		bottom: initial;
	}
	.carousel-item{
		-webkit-transform-style: preserve-3d;
		-moz-transform-style: preserve-3d;
		transform-style: preserve-3d;
	}
</style>
<hr>
<div class = "flex-container">
	<div id="carouselExampleIndicators" class="carousel slide shadow-lg" data-ride="carousel">
		<ol class="carousel-indicators" id = "indicators">
			<li data-target="#carouselExampleIndicators" data-slide-to="0" class="indicator active"></li>
		</ol>
		<div class="carousel-inner" id="inner">
			<div class="carousel-item active">
				<img class="d-block w-100" src="{% static 'images/yellow.png' %}" alt="First slide">
				<div class="carousel-caption d-none d-md-block">
					<h6>Welcome to the New CPFD Resource Center</h6>
					<p>The central location for all forms, links, and more...</p>
				</div>
			</div>
		</div>
		<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			<span class="carousel-control-prev-icon indicator2" aria-hidden="true"></span>
			<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			<span class="carousel-control-next-icon indicator2" aria-hidden="true"></span>
			<span class="sr-only">Next</span>
		</a>
	</div>
	<div class = "topics">
		<a class="anchor" href="{% url 'blog:resources' %}">
			<img class="href shadow-lg" src="{% static 'images/resources.png' %}" class="img-fluid mx-auto d-block">
		</a>
		<a class="anchor" href="{% url 'blog:methods' %}">
			<img class="href shadow-lg" src="{% static 'images/method2.png' %}" class="img-fluid mx-auto d-block">
		</a>
		<a class="anchor" href="{% url 'blog:training' %}">
			<img class="href shadow-lg" src="{% static 'images/learning.png' %}" class="img-fluid mx-auto d-block">
		</a>
	</div>
</div>
<script type="text/javascript">
	var navBar = document.getElementById('navDiv').innerHTML;
	var newBar = `
		<div>
			${navBar}
		</div>`
	document.getElementById('navDiv').innerHTML = newBar;
	document.getElementById('home').remove();

	var objs = JSON.parse("{{text}}".replace(/&quot;/g,'"'));
	
	var indicators = document.getElementById('indicators');
	var inner = document.getElementById('inner');
	for (var i in objs){
		var id = parseInt(i) + 1;
		indicators.innerHTML += `<li data-target="#carouselExampleIndicators" data-slide-to=${id} class="indicator"></li>`

		var slide = `
			<div class="carousel-item">
				<img class="d-block w-100" src="{% static 'images/yellow.png' %}">
				<div class="carousel-caption d-none d-md-block">
					<a href="${objs[i].url}">
						<h6>${objs[i].headline}</h6>
					</a>
					<p>${objs[i].body}</p>
				</div>
			</div>`;
		inner.innerHTML += slide;
	}
	console.log("{{forms}}")
</script>
{% endblock %}

blog/templates/blog/navbar.html
{% load static %}

<style type="text/css">
  nav{
    background-color:#526927 !important;
    border:3px solid  white;
    border-bottom-right-radius:15px;
    border-bottom-left-radius:15px;
  }
  .white{
    color:#fff !important;
  }
  .dropdown-item{
    color: black !important;
  }
  .navbar-nav, a{
    text-align: center;
    justify-content: center;
  }
  li{
    padding-left:10px;
    padding-right:10px;
    border: 1px #fff;
  }
  #topDiv{
    border:3px solid  #8d8299;
  }
  a > img{
    padding-left: 50px;
    display: block;
    height: 70px;
  }
  li > a{
    font-size: 1.3rem;
    font-family: Rockwell, "Courier New", Courier, Georgia,
                 Times, "Times New Roman", serif;
    text-decoration: underline;
    font-weight: 600;
  }
  #searchForm{
    justify-content: center;
  }
</style>
<div id = "navDiv">
  <nav id = "nav" class="navbar navbar-expand-lg navbar-light shadow mx-auto">
  <a id = 'brand' class="navbar-brand white" href="#" style="text-decoration: underline;"><img id='brand' src="{% static 'images/logo4.png' %}" style=></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation" style="border-color:white;color:white;">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item active" id="home">
        <a class="nav-link white" href="{% url 'blog:home' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link white" href="{% url 'blog:methods'%}">Methodology</a>
      </li>
      <li class="nav-item">
        <a class="nav-link white" href="{% url 'blog:resources' %}">CPFD Resources</a>
      </li>
      <li class="nav-item">
        <a class="nav-link white" href="{% url 'blog:training'%}">Learning</a>
      </li>
    </ul>
      <form method="GET" action='' id="searchForm" class="form-inline">
        <input type="search" id="searchBar" class="form-control mr-sm-2" placeholder="Type then click Search..." aria-label="Search">
        <a id="searchRedirect">
          <button type="button" onclick="searchSubmit()" id="searchBtn" class="btn btn-info my-2 my-sm-0">Search</button>
        </a>
      </form>
  </div>
</nav>
</div>
<script type="text/javascript">
  function searchSubmit(){
    var form = document.getElementById('searchBar').value;
    var url = `http://172.20.57.135:88/search/${form}/`;
    if (form != ''){
      window.location.href = url;
    } else {
      window.location.href = 'http://172.20.57.135:88/search/%20/';
    }
  }
</script>

blog/templates/blog/resourceFormUpload.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	body{
		overflow-y: scroll;
	}
	.custom{
		width: auto;
		background-color: #fff;
		justify-content: center;
		display: flex;
		background-color: #829986;
		color:white;
		border-radius: 25px;
		text-decoration: underline;
		border-color: #fff;
		border-width: 4px;
	}
	table{
		width:100%;
	}
	.custom1{
		width: 90%;
		display: flex;
		justify-content: center;
		border-radius: 25px;
		border-color: #2e612f;
		border-width: 2px;
	}
	th, .header{
		background-color: #829986;
		color: white;
		text-align: center;
		border: 1px black;
		font-weight: bold;
	}
	td {
		text-align: center;
	}
	tr { 
		width: 100%;
	}
	a {
		color:black !important;
	}
	{box-sizing: border-box;}

	/* The popup form - hidden by default */
	.form-popup {
	  display: none;
	  position: fixed;
	  bottom: 0;
	  right: 15px;
	  border: 3px solid #f1f1f1;
	  z-index: 9;
	}

	/* Add styles to the form container */
	.form-container {
	  max-width: 600px;
	  padding: 10px;
	  background-color: white;
	}

	/* Full-width input fields */
	.form-container input[type=text], .form-container input[type=password] {
	  width: 100%;
	  padding: 15px;
	  margin: 5px 0 22px 0;
	  border: none;
	  background: #f1f1f1;
	}

	/* Set a style for the submit/login button */
	.form-container .btn {
	  background-color: DodgerBlue;
	  color: white;
	  padding: 16px 20px;
	  border: none;
	  cursor: pointer;
	  width: 100%;
	  margin-bottom:10px;
	  opacity: 0.8;
	}

	/* Add a red background color to the cancel button */
	.form-container .cancel {
	  background-color: red;
	}

	/* Add some hover effects to buttons */
	.form-container .btn:hover, .open-button:hover {
	  opacity: 1;
	}
	h1{
		text-align: center;
	}
	.head{
		padding-top:.5rem;
		padding-left: 8rem;
		padding-right: 8rem;
		padding-bottom: .5rem;
		text-align: center;
	}
	svg{
		color: #007bff
	}
</style>

<hr>
<div class="row">
	<div class="column custom mx-auto">
		<div class="custom card card-body head shadow">
			<h2>CPFD Resource Forms</h2>
		</div>
	</div>
</div>
<br>
<div class="card card-body custom1 mx-auto shadow">
	<div class = "card card-body">
		<div style="display: flex">
			<div style="flex:7">
				<input id="search-input" class="form-control" type="text" placeholder="Begin typing to search through files!">
			</div>
			<div style="flex:1; justify-content: right; padding-left:20px;">
				<button class="btn btn-warning"><a href="{% url 'api:uploadResource' %}">Add New File</a></button>
			</div>			
		</div>
	</div>

	<table class="table table-striped">
		<tr>
			<th data-column="title" data-order="desc">Document Title &#9650</th>
			<th data-column="date" data-order="desc">Date Added &#9650</th>
			<td class = "header">Preview</td>
			<td class = "header">Delete</td>
		</tr>

		<tbody id="myTable">

		</tbody>
	</table>

	<div class="form-popup" id="myForm">
		<form method = 'get' class="form-container">
			<h1>Update</h1>
			
			<label><b>Title: </b></label>
			<input type="text" id="titleUpdate" required>

			<button id = "submitUpdate" type="submit" class="btn">Submit</button>
			<button type="submit" class="btn cancel" onClick="closeForm()">Close</button>
		</form>
	</div>
</div>	

<script type="text/javascript">
	function getCookie(name) {
			let cookieValue = null;
			if (document.cookie && document.cookie !== '') {
				const cookies = document.cookie.split(';');
				for (let i = 0; i < cookies.length; i++) {
					const cookie = cookies[i].trim();
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
						cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
						break;
					}
				}
			}
			return cookieValue;
		}

	const csrftoken = getCookie('csrftoken');
	var activeItem = null;
	var html = null;
	var listSnapshot = [];
	var myData = {}

	function buildTable(data){
		var table = document.getElementById('myTable');
		table.innerHTML= ''
		for (var i =0; i < data.length; i++) {
			try{
				document.getElementById(`data-row-${i}`).remove()
			} catch(err){

			}
			var src = "http://172.20.57.135:88/display3/" + data[i].id
			var date = new Date(data[i].date);
			var adjusted = date.toDateString();
			var row = `
				<tr id = "data-row-${i}">
					<td>${data[i].title}</td>
					<td>${adjusted.substr(adjusted.indexOf(' ') + 1)}</td>
					<td>
						<a id="svg" href=${src}>
							<svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
								<path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
							<path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
							</svg>
						</a>
					</td>
					<td><button class="btn btn-sm btn-outline-danger delete">Delete</button></td>
				</tr>
			`
			table.innerHTML += row
		}
		for (var i=0; i < data.length; i++){
			deleteBtn = document.getElementsByClassName('delete')[i];
			deleteBtn.addEventListener('click', (function(item){
				return function(){
					deleteItem(item);
				}
			})(myData[i]));
		}
		if (listSnapshot.length > data.length){
			for (var i = data.length; i < listSnapshot.length; i++){
				document.getElementById(`data-row-${i}`).remove();
			}
		}
		listSnapshot = data 
	}

	function editItem(item){
		activeItem = item;
		document.getElementById('titleUpdate').value = activeItem.title;
		openForm();
	}


	function searchTable(value, data){
		var filteredData = []
		for (var i =0; i < data.length; i++){
			value = value.toLowerCase()
			var title = data[i].title.toLowerCase()
			if (title.includes(value)){
				filteredData.push(data[i]);
			}
		}

		return filteredData
	}


	function startBuild(){
		var url = "http://172.20.57.135:88/api/form2-list/"
		fetch(url)
		.then((resp) => resp.json())
		.then(function(data) {
			myData = data;
			buildTable(myData);
		});
	}

	function deleteItem(item){
		console.log("Deleting: ", item);
		var url = `http://172.20.57.135:88/api/form2-delete/${item.id}/`
		fetch(url, {
			method:'DELETE',
			headers:{
				'Content-type':'application/json',
				'X-CSRFToken':csrftoken,
			}
		}).then(function(response){
			startBuild();
		})
	}

	startBuild();

	let items = document.getElementsByTagName('th')
	for (let i of items){
		i.addEventListener('click', function(e){
			var column = e.target.dataset.column;
			var order = e.target.dataset.order;
			var text = e.target.innerHTML;
			console.log(text);
			text = text.substring(0, text.length - 1);

			if(order == 'desc'){
				e.target.dataset.order = "asc";
				text += '&#9660';
				myData = myData.sort((a,b) => a[column] > b[column] ? 1:-1);
			} else{
				e.target.dataset.order = "desc";
				text += '&#9650';
				myData = myData.sort((a,b) => a[column] < b[column] ? 1:-1);
			}
			e.target.innerHTML = text;
			buildTable(myData);
		})
	}

	var type = document.getElementById('search-input');
	type.addEventListener('keyup', function(e){
		var value = e.target.value;
		var data = searchTable(value, myData);
		buildTable(data);
	});
</script>
{% endblock %}

blog/templates/blog/resources.html
{% extends 'blog/main.html' %}
{% load static %}
{% block content %}

<style type="text/css">
	.container{
		width:98%;
		justify-content: center;
		display:flex;
		justify-content: center;
	}
	.container2{
		width:40%;
		justify-content: center;
		display:flex;
	}
	.href{
		justify-content: center;
		margin-left: 30px;
		margin-right: 30px;
		border: 3px solid  white;
		outline: 3px solid #829986;
	}
	.head{
		padding-top:.25rem;
		padding-left: 8rem;
		padding-right: 8rem;
		padding-bottom: 0rem;
		text-align: center;
	}
	.custom{
		width: auto;
		justify-content: center;
		display: flex;
		background-color: #526927;
		color:white;
		border-radius: 15px;
		text-decoration: underline;
		border-color: #fff;
		border-width: 2px;
	}
	.head{
		padding-top:.25rem;
		padding-left: 8rem;
		padding-right: 8rem;
		padding-bottom: 0rem;
		text-align: center;
	}
	h3{
    	font-family: Rockwell, "Courier New", Courier, Georgia, Times, "Times New Roman", serif;
    	text-decoration: underline;
	}
</style>
<hr>
<div class="row">
	<div class="column custom mx-auto">
		<div class="custom card card-body head shadow">
			<h3>CPFD Resources</h3>
		</div>
	</div>
</div>
<br>
<br>
<div class = "container">
	<a class="href shadow" href="{% url 'blog:links' %}">
		<span>
			<img src = "{% static 'images/quicklinks.png' %}" class = "img img-fluid mx-auto d-block">
		</span>
	</a>
	<a class="href shadow" href="{% url 'blog:forms' %}">
		<span>
			<img src = "{% static 'images/forms.png' %}" class = "img img-fluid mx-auto d-block">
		</span>
	</a>
</div>
<br>
<div class="container2 mx-auto">
	<a class="href shadow" href="{% url 'blog:support' %}">
		<span>
			<img src = "{% static 'images/technicalsupport.png' %}" class = "img img-fluid mx-auto d-block">
		</span>
	</a>
</div>
<br>
{% endblock %}